# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Murillo Parreira
tagline:          'A Tech Blog'
description:      'Um blog sobre tudo e sobre nada'
url:              http://murparreira.github.io
baseurl:          /

author:
  name:           'Murillo Parreira'
  url:            https://twitter.com/murifox

paginate:         5

# Custom vars
version:          2.1.0

github: http://github.com/murparreira
twitter: http://twitter.com/murifox
stackoverflow: http://stackoverflow.com/users/1023609/murifox
instagram: http://instagram.com/murifox
